name: 'cue_dbt'
version: '1.0.0'
config-version: 2

profile: 'cue_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  cue_dbt:
    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: view
      +schema: intermediate

    marts:
      +materialized: table
      marketing:
        +schema: marketing
      mathgym:
        +schema: mathgym
      mathfit_tests:
        +schema: mathfit_tests

seeds:
  cue_dbt:
    +schema: seeds

snapshots:
  cue_dbt:
    +schema: snapshots
    +strategy: check
    +unique_key: lead_id

vars:
  marketing_start_date: '2022-04-01'
  superleap_cutover_date: '2026-04-01'
  mathgym_launch_date: '2026-02-11'

# Elementary writes its run + test results to this schema
models:
  elementary:
    +schema: elementary
    +materialized: table
