name: 'cue_dbt'
version: '1.0.0'
config-version: 2

flags:
  require_explicit_package_overrides_for_builtin_materializations: false

dispatch:
  - macro_namespace: elementary
    search_order: ['cue_dbt', 'elementary']

profile: 'cue_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  cue_dbt:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table

  elementary:
    +materialized: table

seeds:
  cue_dbt: {}

snapshots:
  cue_dbt:
    +strategy: check
    +unique_key: lead_id

vars:
  marketing_start_date: '2022-04-01'
  superleap_cutover_date: '2026-04-01'
  mathgym_launch_date: '2026-02-11'
